# -*- coding: utf-8 -*-
"""FINALFINAL_PY.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dl3ere28Ahkg7QcA-8md0qxeSnu-KIX4

# CSE 151B Competition — Starter Notebook

Welcome to the **CSE 151B Spring 2026 Math Reasoning Competition**!  
This notebook walks you through the full pipeline end-to-end:

1. Setting up the Python environment with `uv`
2. Loading the competition dataset
3. Running inference with **Qwen3-4B-Thinking** via vLLM (INT8 quantized)
4. Scoring responses against ground-truth answers
5. Saving results to JSONL for submission

The public dataset (`public.jsonl`) contains questions **with** answers so you can measure accuracy locally.  
The private test set used for the leaderboard does **not** include answers — for that, skip evaluation and submit the raw responses.

## 1. Environment Setup

We use [`uv`](https://github.com/astral-sh/uv) for fast, reproducible package management.

The steps below:
1. Install `uv` into `~/.local/bin`
2. Create a virtual environment at `.venv/`
3. Install all required packages (This might take a while)

> **After running this cell, restart the kernel** so that the newly installed packages (especially `vllm` and `transformers`) are picked up by the current Python session.

### Comment Out the cell below after first installation.
"""

# Install uv
# !wget -qO- https://astral.sh/uv/install.sh | sh

# Create a virtual environment
# !uv venv .venv --seed

# Install dependencies — this is fast thanks to uv's parallel resolver
# !.venv/bin/python -m pip install sympy numpy transformers vllm tqdm bitsandbytes antlr4-python3-runtime==4.11.1 ipykernel jupyter

# Install Jupyter Kernel
# !.venv/bin/python -m ipykernel install --user --name cse151b --display-name "Python (cse151b)"

# print("Done. Restart the kernel before proceeding.")
# print("Selection process: on top right, click on current kernel '(ususally named python)' -> 'select another kernel' -> 'Jupyter Kernel' -> 'Python (cse151b)'.")

"""### Run the cell below every time to activate the installed environment."""

# activate venv after installation. This needs to be run everytime.
#!source ./.venv/bin/activate
# print("Make sure the current kernel is 'Python (cse151b)' before proceeding")

"""## 2. Imports & Configuration

All key settings are collected in one place.  
- `DATA_PATH` — public dataset with ground-truth answers (use this to measure accuracy)
- `OUTPUT_PATH` — where per-question results will be written
- `GPU_ID` — which GPU to use (update if your machine has a different device index)
- `MAX_TOKENS` — maximum tokens the model may generate per response
"""

import json
import os

# ── Configuration ─────────────────────────────────────────────────────────────
MODEL_ID    = "Qwen/Qwen3-4B-Thinking-2507"
GPU_ID      = "0"
DATA_PATH   = "data/private.jsonl"
OUTPUT_PATH = "results/private_results.jsonl"
MAX_TOKENS  = 32768

os.environ["CUDA_VISIBLE_DEVICES"] = GPU_ID

import re
import sys
from pathlib import Path
from typing import Optional

from transformers import AutoTokenizer
from vllm import LLM, SamplingParams
from tqdm import tqdm

from collections import Counter
from tqdm import tqdm

from latex2sympy2_extended import latex2sympy

"""## 3. Load the Dataset

The dataset is stored as newline-delimited JSON (`.jsonl`). Each line is one question with the following fields:

| Field | Description |
|---|---|
| `id` | Unique question identifier |
| `question` | Problem statement |
| `options` | List of answer choices — present for **MCQ**, absent for **free-form** |
| `answer` | Ground-truth answer (letter for MCQ, value/list for free-form) |
"""

data = [json.loads(line) for line in open(DATA_PATH)]

n_mcq  = sum(bool(d.get("options")) for d in data)
n_free = sum(not d.get("options")   for d in data)
print(f"Loaded {len(data)} questions  ({n_mcq} MCQ, {n_free} free-form)")

# Preview one MCQ and one free-form item
mcq_sample  = next(d for d in data if d.get("options"))
free_sample = next(d for d in data if not d.get("options"))

print("\n── MCQ sample ──")
print(json.dumps(mcq_sample, indent=2))
print("\n── Free-form sample ──")
print(json.dumps(free_sample, indent=2))

import pandas as pd

df_data = pd.DataFrame(data)
# display(df_data.head())

"""## 4. Prompt Construction

We use two system prompts depending on the question type:

- **MCQ** — the model must select the best answer letter and wrap it in `\boxed{}`
- **Free-form** — the model solves step-by-step and puts the final answer in `\boxed{}`

`build_prompt()` returns the appropriate `(system, user)` pair for each item.
"""

SYSTEM_PROMPT_MATH = (
    """
You are a research mathematician. Please provide a clear and step-by-step solution for a mathematical problem. Conclude the answer by stating "The answer is therefore \\boxed{[ANSWER]}."
## If the problem has multiple [ANS] placeholders, place all answers inside that one box, comma-separated, in placeholder order. ##
## ANY APPROXIMATION IS STRICTLY FORBIDDEN ##
## USE EXACT SYMBOLIC EXPRESSIONS ONLY ##
    """
)

SYSTEM_PROMPT_EMBEDDED_MCQ = (
    """
You are a research mathematician. Please provide a clear and step-by-step solution for a mathematical problem. Conclude the answer by stating "The answer is therefore \\boxed{[ANSWER]}."
## If the problem has multiple [ANS] placeholders, place all answers inside that one box, comma-separated, in placeholder order. ##
## ANY APPROXIMATION IS STRICTLY FORBIDDEN ##
## USE EXACT SYMBOLIC EXPRESSIONS ONLY ##
    """
)

SYSTEM_PROMPT_MCQ = (
    """
You are a research mathematician. Please provide a step-by-step solution for a mathematical problem. Conclude the answer by stating "The answer is therefore \\boxed{[ANSWER]}."
If two options look different but are mathematically equivalent, choose the equivalent option.
## Your answer inside that one box must contain ONLY the chosen uppercase option letter ##
## USE EXACT SYMBOLIC EXPRESSIONS ONLY ##
    """
)

def options_in_FRQ(question: str) -> bool:
    return bool(re.search(r"\bA[\.\)]\s+", question) and re.search(r"\bB[\.\)]\s+", question))

def number_ANS(question: str) -> int:
    return question.count("[ANS]")

def build_prompt(question: str, options: Optional[list]) -> tuple[str, str]:
    """Return (system_prompt, user_prompt) for a question."""
    if options:
        labels    = [chr(65 + i) for i in range(len(options))]
        opts_text = "\n".join(f"{lbl}. {opt.strip()}" for lbl, opt in zip(labels, options))
        user_prompt_MCQ = (
            f"{question}\n\nOptions:\n{opts_text}"
        )
        return SYSTEM_PROMPT_MCQ, user_prompt_MCQ

    n_ANS = number_ANS(question)

    if options_in_FRQ(question): #Q6, Q80
        user_prompt_EMBEDDED_MCQ = (
            f"{question}\n\n"
            f"This problem has {n_ANS} [ANS] placeholder{'s' if n_ANS != 1 else ''}; each should be filled by a single uppercase letter chosen from the options listed inside the question."
        )
        return SYSTEM_PROMPT_EMBEDDED_MCQ, user_prompt_EMBEDDED_MCQ

    expected = max(n_ANS, 1)

    user_prompt_FRQ = (
        f"{question}\n\n"
        f"This problem expects exactly {expected} answer{'s' if expected != 1 else ''} inside \\boxed{{}}."
    )
    return SYSTEM_PROMPT_MATH, user_prompt_FRQ


# Verify with samples
for label, item in [("MCQ", mcq_sample), ("Free-form", free_sample)]:
    sys_p, usr_p = build_prompt(item["question"], item.get("options"))
    print(f"── {label} user prompt (first 200 chars) ──")
    print(usr_p[:200], "...\n")

"""## 5. Load Model with vLLM (for general case, vLLM is faster)

We load **Qwen3-4B-Thinking-2507** with **INT8 quantization** via BitsAndBytes.  
Setting `load_format="bitsandbytes"` tells vLLM to apply on-the-fly INT8 weight quantization, roughly halving GPU memory usage compared to BF16.

Key parameters:
- `gpu_memory_utilization` — fraction of GPU VRAM reserved for the model and KV cache
- `max_model_len` — maximum sequence length (prompt + generation)
- `max_num_seqs` — maximum number of sequences processed in parallel
"""

tokenizer = AutoTokenizer.from_pretrained(MODEL_ID)
tokenizer.pad_token = tokenizer.eos_token

llm = LLM(
    model=MODEL_ID,
    enable_prefix_caching=False,
    gpu_memory_utilization=0.95,
    max_model_len=20000,
    trust_remote_code=True,
    max_num_seqs=64,
    max_num_batched_tokens=20000,
)

sampling_params = SamplingParams(
    bad_words=[
    "≈", " ≈",
    "\\approx", " \\approx",
    " approximately", " Approximately",
    # " roughly", " Roughly",
    # " about ", " around ",
    ],
    n=1,
    max_tokens=20000,
    temperature=0.6,
    top_p=0.95,
    top_k=20,
    min_p=0.0,
    presence_penalty=0.0,
    repetition_penalty=1.0,
)

retry_params = SamplingParams(
    n=1,
    max_tokens=20000,
    temperature=0.0,
    top_k=-1,
)

print("Model loaded.")

"""## 5. Load Model with Transformers (alternative to vLLM for DataHub)

We load **Qwen3-4B-Thinking-2507** with **INT4 quantization** via BitsAndBytes.  

Key parameters:
- `load_in_4bit` — quantization strategy of INT4

## 6. Generate Responses

We format every question into a chat-template prompt, then call `llm.generate()` in one batched pass.  
vLLM handles batching and scheduling internally — no manual batching needed.

### Generate with vLLM
"""

sys.path.insert(0, ".")
from judger import Judger
judger = Judger(strict_extract=False)

def extract_MCQ(text: str) -> str:
    ans = ""
    if "\\boxed{" in text:
        try:
            ans = judger.extract_boxed_answer(text)
            if ans == text:
                ans = ""
        except:
            ans = ""

    if ans:
        m = re.match(r"\s*([A-Za-z])\s*$", ans)
        if m:
            return m.group(1).upper()
        m = re.search(r"\b([A-J])\b", ans)
        if m:
            return m.group(1).upper()

    tail = text[-1500:]
    for pat in [r"answer\s*(?:is|:)?\s*\(?\b([A-J])\b",
                r"\bOption\s+([A-J])\b",
                r"choose\s+\(?\b([A-J])\b"]:
        m = list(re.finditer(pat, tail, re.I))
        if m:
            return m[-1].group(1).upper()

    return ""

def extract_FRQ(text: str) -> str:
    if "\\boxed{" not in text:
        return []

    try:
        ans = judger.extract_boxed_answer(text)

        if not ans or ans == text:
            return []

        parts = judger.split_by_comma(ans)
        return [judger.norm_ans_str(p) for p in parts]

    except:
        return []

def vote_MCQ(samples):
    counter = Counter()
    rep = {}
    for s in samples:
        l = extract_MCQ(s)
        if l:
            counter[l] += 1
            rep.setdefault(l, s)
    if not counter:
        finished = [s for s in samples if "</think>" in s]
        return (finished or samples)[0]
    return rep[counter.most_common(1)[0][0]]

def vote_FRQ(samples, n_slots):
    slots = [Counter() for _ in range(n_slots)]
    for s in samples:
        parts = extract_FRQ(s)
        if len(parts) != n_slots:
            continue
        for i, p in enumerate(parts):
            slots[i][p] += 1
    if any(len(c) == 0 for c in slots):
        finished = [s for s in samples if "</think>" in s]
        return (finished or samples)[0]

    finished = [s for s in samples if "</think>" in s]
    return (finished or samples)[0].rstrip() + "\n\nThe final answer after Self-Consistency is \\boxed{" + ", ".join(c.most_common(1)[0][0] for c in slots) + "}."

# Build prompts for first 5 entries
prompts = []
for item in data:
    system, user = build_prompt(item["question"], item.get("options"))
    prompt_text = tokenizer.apply_chat_template(
        [{"role": "system", "content": system},
         {"role": "user",   "content": user}],
        tokenize=False,
        add_generation_prompt=True,
    )
    prompts.append(prompt_text)

# Generate
print(f"Generating responses for {len(prompts)} questions...")
outputs = llm.generate(prompts, sampling_params=sampling_params)

responses = []
needs_retry = []
for idx, (item, out) in enumerate(zip(data, outputs)):
    samples = [o.text.strip() for o in out.outputs]

    if item.get("options"):
        chosen = vote_MCQ(samples)
    else:
        n_slots = max(number_ANS(item["question"]), 1)
        chosen = vote_FRQ(samples, n_slots)

    responses.append(chosen)
    # Flag for retry the chosen response does not contain a final \boxed{}
    if "\\boxed{" not in chosen[-1500:]:
        needs_retry.append(idx)

# Retry pass
if needs_retry:
    print(f"Retrying {len(needs_retry)} truncated items...")
    retry_prompts = []
    for i in needs_retry:
        item = data[i]
        sys_p, usr_p = build_prompt(item["question"], item.get("options"))

        # Add a strong hint
        usr_p2 = (
            usr_p
            + "\n\nIMPORTANT: Solve as concisely as possible and put the FINAL\
                answer in \\boxed{} at the end. Do not second-guess yourself;\
                commit to the answer."
        )

        retry_prompts.append(tokenizer.apply_chat_template(
            [{"role":"system","content":sys_p},{"role":"user","content":usr_p2}],
            tokenize=False, add_generation_prompt=True,
        ))

    retry_outs = llm.generate(retry_prompts, sampling_params=retry_params)

    for i, retry_output in zip(needs_retry, retry_outs):
        new_response = retry_output.outputs[0].text.strip()
        if "\\boxed{" in new_response:
            responses[i] = new_response

# post-processing
sys.path.insert(0, ".")
from judger import Judger
judger = Judger(strict_extract=False)

DECIMAL  = re.compile(r"^-?\d+(\.\d+)?([eE][+-]?\d+)?$")
LETTER   = re.compile(r"^[A-Z]$")
TRUE  = {"T", "true", "True", "TRUE"}
FALSE = {"F", "false", "False", "FALSE"}
YES = {"yes", "Yes", "YES"}
NO = {"no", "No", "NO"}


def extract_ANS(text: str):
    if "\\boxed{" not in text:
        return []
    try:
        ans = judger.extract_boxed_answer(text)
        if not ans or ans == text:
            return []
        ans_list = judger.split_by_comma(ans)
        return ans_list
    except:
        return []


def normalize_bool(ans_field):
    ans = ans_field.strip()
    if ans in TRUE:  return "T"
    if ans in FALSE: return "F"
    if ans in YES:  return "yes"
    if ans in NO: return "no"
    return None


def coerce(ans_field, is_mcq=False):
    ans = ans_field.strip()
    if not ans:
        return ans_field

    if is_mcq:
        choice = re.search(r"\b([A-Z])\b", ans)
        return choice.group(1) if choice else ans

    bool_norm = normalize_bool(ans)
    if bool_norm is not None:
        return bool_norm

    if DECIMAL.match(ans):
        return ans

    if LETTER.match(ans):
        return ans

    try:
        expr = latex2sympy(ans)
        if hasattr(expr, "free_symbols") and not expr.free_symbols:
            val = expr.evalf(20)
            if val.is_real and val.is_finite:
                return str(val)
    except Exception:
        pass

    return ans


def post_process(response, is_mcq=False):
    try:
        ans_list = extract_ANS(response)
        if not ans_list:
            return response

        new_box = ", ".join(coerce(ans, is_mcq=is_mcq) for ans in ans_list)
        if new_box.strip() == judger.extract_boxed_answer(response).strip():
            return response
        return response.rstrip() + f"\n\nCoerced final answer: \\boxed{{{new_box}}}"
    except Exception:
        return response

for i in range(len(responses)):
    item = data[i]
    before = responses[i]
    responses[i] = post_process(before, is_mcq=bool(item.get("options")))

"""## 7. Score Responses

Scoring differs by question type:

- **MCQ**: extract the predicted letter from `\boxed{}` and compare to the gold letter (exact match).
- **Free-form**: use `Judger.auto_judge()` which handles symbolic and numeric equivalence.

Each result record contains `{id, is_mcq, gold, response, correct}`.
"""

def score_mcq(response: str, gold_letter: str) -> bool:
    return extract_MCQ(response) == gold_letter.strip().upper()


# Load Judger for free-form scoring
sys.path.insert(0, ".")
from judger import Judger
judger = Judger(strict_extract=False)

results = []
for item, response in tqdm(zip(data, responses), total=len(data), desc="Scoring"):
    is_mcq = bool(item.get("options"))
    # gold   = item["answer"]

    # if is_mcq:
    #     correct = score_mcq(response, str(gold))
    # else:
    #     gold_list = gold if isinstance(gold, list) else [gold]
    #     try:
    #         correct = judger.auto_judge(
    #             pred=response,
    #             gold=gold_list,
    #             options=[[]] * len(gold_list),
    #         )
    #     except Exception:
    #         correct = False

    results.append({
        "id":       item.get("id"),
        "is_mcq":   is_mcq,
        # "gold":     gold,
        "response": response,
        # "correct":  correct,
    })

print(f"Scoring complete. {len(results)} results.")

"""## 8. Summary

Print accuracy broken down by question type.
"""

# mcq_res  = [r for r in results if r["is_mcq"]]
# free_res = [r for r in results if not r["is_mcq"]]

# def acc(subset):
#     return sum(r["correct"] for r in subset) / len(subset) * 100 if subset else 0.0

# print("=" * 50)
# print("EVALUATION RESULTS")
# print("=" * 50)
# print(f"  MCQ        : {sum(r['correct'] for r in mcq_res):4d} / {len(mcq_res):4d}  ({acc(mcq_res):.2f}%)")
# print(f"  Free-form  : {sum(r['correct'] for r in free_res):4d} / {len(free_res):4d}  ({acc(free_res):.2f}%)")
# print(f"  Overall    : {sum(r['correct'] for r in results):4d} / {len(results):4d}  ({acc(results):.2f}%)")
# print("=" * 50)

"""## 9. Save Results

Results are written as newline-delimited JSON.

**With evaluation** (public set — you have ground-truth):  
Each line: `{id, is_mcq, gold, response, correct}`

**Without evaluation** (private test set — no ground-truth available):  
Each line: `{id, is_mcq, response}` — omit `gold` and `correct`.

Toggle `SAVE_EVAL` below accordingly.
"""

SAVE_EVAL = False   # Set to False when running on the private test set

out_path = Path(OUTPUT_PATH)
out_path.parent.mkdir(parents=True, exist_ok=True)

with open(out_path, "w") as f:
    for r in results:
        if SAVE_EVAL:
            record = {"id": r["id"], "is_mcq": r["is_mcq"], "gold": r["gold"],
                      "response": r["response"], "correct": r["correct"]}
        else:
            record = {"id": r["id"], "is_mcq": r["is_mcq"], "response": r["response"]}
        f.write(json.dumps(record) + "\n")

print(f"Saved {len(results)} records to {out_path}")

jsonl_file = pd.read_json("results/private_results.jsonl", lines=True)

jsonl_file.to_csv("results/submission.csv", index=False)

"""## Next Steps

This notebook gives you a working baseline. Here are directions to improve your score:

- **Prompt engineering** — try different system prompts or few-shot examples inside the user turn
- **Sampling parameters** — adjust `temperature`, `top_p`, or use majority voting across multiple samples
- **Fine-tuning** — the competition allows model fine-tuning; see the course resources for guidance

Good luck!
"""